#ifndef FILEMANAGER_H
#define FILEMANAGER_H

#include <vector>
#include "vertex.h"

class LandscapeComponent;
/** Is responsible for reading and writing to files, such as meshes and scripts.
 */
class FileManager
{
public:
    FileManager();
    ~FileManager();

    /** Reads a .txt file into a vector of unindiced vertices.
       @param filename: the name of the file to read, without the path.
       @return A vector of vertices.
     */
    std::vector<Vertex> readFile(std::string filename);

    /** Writes a set of vertices into a .txt file, in a format that can be read with readFile().
       @param inVertices: The vertices to write into a file.
       @param filename: the name of the file, without the path.
     */
    void writeFile(std::vector<Vertex> inVertices, std::string filename);

    /** Reads an .obj file into a set of vertices and indices.
       The indices actually just go from 0 to vertices.size()-1, so theres not really any use for them.
       @param filename: the name of the file to read, without the path.
       @return A pair of vectors, the first has the vertices, the second has the indices.
     */
    std::pair<std::vector<Vertex>, std::vector<unsigned int>> readOBJFile(std::string filename);

    /** Reads a .bmp image as a heigth map, and generates vertices from it and the LandscapeComponent.
     * @param filename: The filename of the heightmap. Needs the entire filepath.
     * @param lComp: The belonging LandscapeComponent. Holds importan variables for reading,
               such as min and max values im each axis, and distance between vertices
     * @return The vertices generated by the height map and the LandscapeComponent.
     */
    std::vector<Vertex> readHeightMap(QString filename, LandscapeComponent* lComp);

    /** Writes a landscape into a height map.
        1 vertex becomes 1 pixel.
       @param filename: the name of the heigth map. Needs the entire filepath.
       @param lComp: The landscape we are saving.
       @param vertices: The vertices we are saving.
     */
    void writeHeightMap(QString filename, const LandscapeComponent *lComp,  std::vector<Vertex> vertices);

    /** Reads a scipt file into a QString.
       @param filename: The name of the file. Needs the entire filepath.
       @return A QString with all the contents of the string.
     */
    QString readScriptFile(QString filename);


};

#endif // FILEMANAGER_H
